import { Injectable } from '@angular/core';
import {
  IBlog,
  ICarousel,
  IDetails,
  INav,
  IProduct,
} from '../interfaces/data.model';
import { BehaviorSubject } from 'rxjs';
@Injectable({
  providedIn: 'root',
})
export class DataService {
  constructor() {}
  details$: BehaviorSubject<IDetails> = new BehaviorSubject<IDetails>({
    id: 0,
    path: '',
    productName: '',
    productSpecies: '',
    price: '',
    salesPrice: '',
  });
  navData: INav[] = [
    { id: 1, text: 'ავეჯი', special: false },
    { id: 2, text: 'გარე ავეჯი', special: false },
    { id: 3, text: 'კაფე & ბარი', special: false },
    { id: 4, text: 'საოფისე ავეჯი', special: false },
    { id: 5, text: 'სამზარეულო', special: false },
    { id: 6, text: 'დეკორი', special: false },
    { id: 7, text: 'განათება', special: false },
    { id: 8, text: 'სამზარეულოს აქსესუარები', special: false },
    { id: 9, text: 'ტექსტილი', special: false },
    { id: 10, text: 'Summer Sale', special: true },
    { id: 11, text: 'შეთავაზებები', special: true },
  ];

  carouselData: ICarousel[] = [
    {
      id: 1,
      path: 'https://icrhome.ge/assets/images/main_page_banners/668e3202bd8e841fa421e2bf.jpg',
    },
    {
      id: 2,
      path: 'https://icrhome.ge/assets/images/main_page_banners/65031b43bd8e8437fdb32be0.jpg',
    },
    {
      id: 3,
      path: 'https://icrhome.ge/assets/images/main_page_banners/6655864ebd8e840351cb43cf.jpg',
    },
    {
      id: 4,
      path: 'https://icrhome.ge/assets/images/main_page_banners/666ac13fbd8e841fa3910216.jpg',
    },
    {
      id: 5,
      path: 'https://icrhome.ge/assets/images/main_page_banners/6655864ebd8e840351cb43cf.jpg',
    },
  ];
  carousel2Data: ICarousel[] = [
    {
      id: 1,
      path: 'https://icrhome.ge/assets/images/categories/f19cce0aa62b11edbc179600004af6a4.jpg',
    },
    {
      id: 2,
      path: 'https://icrhome.ge/assets/images/categories/18cbc65ca62c11edbc179600004af6a4.jpg',
    },
    {
      id: 3,
      path: 'https://icrhome.ge/assets/images/categories/2b9c0558a62c11edbc179600004af6a4.jpg',
    },
    {
      id: 4,
      path: 'https://icrhome.ge/assets/images/categories/4b47eeeea62c11edbc179600004af6a4.jpg',
    },
    {
      id: 5,
      path: 'https://icrhome.ge/assets/images/categories/81758c9019b411efbc179600004af6a4.jpg',
    },
    {
      id: 6,
      path: 'https://icrhome.ge/assets/images/categories/88f6f49ca62c11edbc179600004af6a4.jpg',
    },
    {
      id: 7,
      path: 'https://icrhome.ge/assets/images/categories/5b8c1082a62c11edbc179600004af6a4.jpg',
    },
    {
      id: 8,
      path: 'https://icrhome.ge/assets/images/categories/68c78ad8a62c11edbc179600004af6a4.jpg',
    },
    {
      id: 9,
      path: 'https://icrhome.ge/assets/images/categories/3ac89dba218e11eebc179600004af6a4.jpg',
    },
  ];
  logoData: ICarousel[] = [
    {
      id: 1,
      path: 'https://icrhome.ge/assets/images/brands/0942620abd3a11ea89549600004af6a4.svg',
    },
    {
      id: 2,
      path: 'https://icrhome.ge/assets/images/brands/f7ad1faea26211ea89549600004af6a4.svg',
    },
    {
      id: 3,
      path: 'https://icrhome.ge/assets/images/brands/9453616c52da11eebc179600004af6a4.svg',
    },
    {
      id: 4,
      path: 'https://icrhome.ge/assets/images/brands/e3564f76a26211ea89549600004af6a4.svg',
    },
    {
      id: 5,
      path: 'https://icrhome.ge/assets/images/brands/6fe3be65fb9a11ec9d649600004af6a4.svg',
    },
    {
      id: 6,
      path: 'https://icrhome.ge/assets/images/brands/463ef4c91ef011eebc179600004af6a4.svg',
    },
    {
      id: 7,
      path: 'https://icrhome.ge/assets/images/brands/1ee476f3bfea11ec9d649600004af6a4.svg',
    },
  ];

  productArr1: IProduct[] = [
    {
      title: 'ყველაზე გაყიდვადი',
      details: [
        {
          id: 1,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007601602-ARM_1.png',
          productName: 'laboratory my home',
          productSpecies: 'table',
          price: '250',
          salesPrice: undefined,
        },
        {
          id: 2,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276000689669-ARM_1.png',
          productName: 'sports shoes',
          productSpecies: 'shoes',
          price: '120',
          salesPrice: '100',
        },
        {
          id: 3,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/XET-8579_1.jpg',
          productName: 'gym equipment',
          productSpecies: 'equipment',
          price: '500',
          salesPrice: undefined,
        },
        {
          id: 4,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/MB-Y-POUF-GR-21_1.jpg',
          productName: 'running shoes',
          productSpecies: 'shoes',
          price: '130',
          salesPrice: '110',
        },
        {
          id: 5,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/HS3048T-TAB_1.jpg',
          productName: 'sports jacket',
          productSpecies: 'jacket',
          price: '200',
          salesPrice: '180',
        },
        {
          id: 6,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007601602-ARM_1.png',
          productName: 'fitness tracker',
          productSpecies: 'accessory',
          price: '150',
          salesPrice: undefined,
        },
        {
          id: 7,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/2085B-BLACK_1.jpg',
          productName: 'yoga mat',
          productSpecies: 'mat',
          price: '60',
          salesPrice: undefined,
        },
        {
          id: 8,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007601602-ARM_1.png',
          productName: 'swimming goggles',
          productSpecies: 'goggles',
          price: '40',
          salesPrice: '30',
        },
        {
          id: 9,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/2085B-BLACK_1.jpg',
          productName: 'hiking boots',
          productSpecies: 'boots',
          price: '180',
          salesPrice: undefined,
        },
        {
          id: 10,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/MB-Y-POUF-GR-21_1.jpg',
          productName: 'camping tent',
          productSpecies: 'tent',
          price: '300',
          salesPrice: '250',
        },
        {
          id: 11,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/XET-8579_1.jpg',
          productName: 'backpack',
          productSpecies: 'bag',
          price: '100',
          salesPrice: '80',
        },
        {
          id: 12,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/2085B-BLACK_1.jpg',
          productName: 'winter jacket',
          productSpecies: 'jacket',
          price: '350',
          salesPrice: '300',
        },
      ],
    },
    {
      title: 'SUMMER SALE',
      details: [
        {
          id: 13,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/FB087-120-BR_1.jpg',
          productName: 'laboratory my home',
          productSpecies: 'table',
          price: '250',
          salesPrice: '125',
        },
        {
          id: 14,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/BI-BEL00024_1.png',
          productName: 'sports shoes',
          productSpecies: 'shoes',
          price: '120',
          salesPrice: '100',
        },
        {
          id: 15,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/7586-WALES170-3S_1.jpg',
          productName: 'gym equipment',
          productSpecies: 'equipment',
          price: '500',
          salesPrice: '350',
        },
        {
          id: 16,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/LG-7750591_1.png',
          productName: 'running shoes',
          productSpecies: 'shoes',
          price: '130',
          salesPrice: '110',
        },
        {
          id: 17,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/SAM00654_1.jpg',
          productName: 'sports jacket',
          productSpecies: 'jacket',
          price: '200',
          salesPrice: '180',
        },
        {
          id: 18,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/MARIS-3S-GR126_1.jpg',
          productName: 'fitness tracker',
          productSpecies: 'accessory',
          price: '150',
          salesPrice: '100',
        },
        {
          id: 19,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/SF-3741L-M7363-A55_1.jpg',
          productName: 'yoga mat',
          productSpecies: 'mat',
          price: '60',
          salesPrice: '40',
        },
        {
          id: 20,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/LG-7750591_1.png',
          productName: 'swimming goggles',
          productSpecies: 'goggles',
          price: '40',
          salesPrice: '30',
        },
        {
          id: 21,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/7586-WALES170-3S_1.jpg',
          productName: 'hiking boots',
          productSpecies: 'boots',
          price: '180',
          salesPrice: '150',
        },
        {
          id: 22,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/LG-7751881_1.png',
          productName: 'camping tent',
          productSpecies: 'tent',
          price: '300',
          salesPrice: '250',
        },
      ],
    },
    {
      title: 'ახალი კოლექცია NATERIAL-ში',
      details: [
        {
          id: 23,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007599886-ARM_1.png',
          productName: 'laboratory my home',
          productSpecies: 'table',
          price: '250',
          salesPrice: '100',
        },
        {
          id: 24,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007271782-ARM_1.png',
          productName: 'sports shoes',
          productSpecies: 'shoes',
          price: '120',
          salesPrice: undefined,
        },
        {
          id: 25,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276000400714-ARM_1.jpg',
          productName: 'gym equipment',
          productSpecies: 'equipment',
          price: '500',
          salesPrice: '300',
        },
        {
          id: 26,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007104325-HM_1.jpg',
          productName: 'running shoes',
          productSpecies: 'shoes',
          price: '130',
          salesPrice: undefined,
        },
        {
          id: 27,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007267532-UMB_1.png',
          productName: 'sports jacket',
          productSpecies: 'jacket',
          price: '200',
          salesPrice: '180',
        },
        {
          id: 28,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276000422600-BBT_1.jpg',
          productName: 'fitness tracker',
          productSpecies: 'accessory',
          price: '150',
          salesPrice: undefined,
        },
        {
          id: 29,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007600308-OCC_1.png',
          productName: 'yoga mat',
          productSpecies: 'mat',
          price: '60',
          salesPrice: undefined,
        },
        {
          id: 30,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007268195-HM_1.png',
          productName: 'swimming goggles',
          productSpecies: 'goggles',
          price: '40',
          salesPrice: '30',
        },
        {
          id: 31,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007396744-CH_1.png',
          productName: 'hiking boots',
          productSpecies: 'boots',
          price: '180',
          salesPrice: undefined,
        },
        {
          id: 32,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276000422600-BBT_1.jpg',
          productName: 'camping tent',
          productSpecies: 'tent',
          price: '300',
          salesPrice: '250',
        },
        {
          id: 33,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276000400714-ARM_1.jpg',
          productName: 'backpack',
          productSpecies: 'bag',
          price: '100',
          salesPrice: '80',
        },
        {
          id: 34,
          path: 'https://icrhome.ge/dist/assets/images/catalog/250/NT-3276007599886-ARM_1.png',
          productName: 'winter jacket',
          productSpecies: 'jacket',
          price: '350',
          salesPrice: undefined,
        },
      ],
    },
  ];
  products: IDetails[] = [
    {
      id: 35,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T117-BROWN_1.jpg',
      productName: 'style chair',
      productSpecies: 'chair',
      price: '650',
      salesPrice: undefined,
    },
    {
      id: 36,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093S-BLACK_1.jpg',
      productName: 'wooden table',
      productSpecies: 'table',
      price: '950',
      salesPrice: '700',
    },
    {
      id: 37,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093-BLACK_1.jpg',
      productName: 'luxury sofa',
      productSpecies: 'sofa',
      price: '1200',
      salesPrice: undefined,
    },
    {
      id: 38,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092PRO-GOLD_1.jpg',
      productName: 'office desk',
      productSpecies: 'desk',
      price: '800',
      salesPrice: '600',
    },
    {
      id: 39,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092-600-BLACK_1.jpg',
      productName: 'dining table',
      productSpecies: 'table',
      price: '550',
      salesPrice: undefined,
    },
    {
      id: 40,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T117-BROWN_1.jpg',
      productName: 'modern lamp',
      productSpecies: 'lamp',
      price: '300',
      salesPrice: '150',
    },
    {
      id: 41,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093S-BLACK_1.jpg',
      productName: 'classic chair',
      productSpecies: 'chair',
      price: '420',
      salesPrice: undefined,
    },
    {
      id: 42,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093-BLACK_1.jpg',
      productName: 'coffee table',
      productSpecies: 'table',
      price: '290',
      salesPrice: undefined,
    },
    {
      id: 43,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092PRO-GOLD_1.jpg',
      productName: 'bedroom dresser',
      productSpecies: 'dresser',
      price: '750',
      salesPrice: undefined,
    },
    {
      id: 44,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092-600-BLACK_1.jpg',
      productName: 'outdoor bench',
      productSpecies: 'bench',
      price: '330',
      salesPrice: undefined,
    },
    {
      id: 45,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T117-BROWN_1.jpg',
      productName: 'patio chair',
      productSpecies: 'chair',
      price: '450',
      salesPrice: undefined,
    },
    {
      id: 46,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093S-BLACK_1.jpg',
      productName: 'rustic table',
      productSpecies: 'table',
      price: '650',
      salesPrice: undefined,
    },
    {
      id: 47,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093-BLACK_1.jpg',
      productName: 'modern couch',
      productSpecies: 'couch',
      price: '1350',
      salesPrice: undefined,
    },
    {
      id: 48,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092PRO-GOLD_1.jpg',
      productName: 'bedside table',
      productSpecies: 'table',
      price: '290',
      salesPrice: undefined,
    },
    {
      id: 49,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092-600-BLACK_1.jpg',
      productName: 'living room set',
      productSpecies: 'set',
      price: '1800',
      salesPrice: undefined,
    },
    {
      id: 50,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T117-BROWN_1.jpg',
      productName: 'vintage bookshelf',
      productSpecies: 'bookshelf',
      price: '580',
      salesPrice: undefined,
    },
    {
      id: 51,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093S-BLACK_1.jpg',
      productName: 'elegant table',
      productSpecies: 'table',
      price: '780',
      salesPrice: undefined,
    },
    {
      id: 52,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093-BLACK_1.jpg',
      productName: 'office chair',
      productSpecies: 'chair',
      price: '320',
      salesPrice: undefined,
    },
    {
      id: 53,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092PRO-GOLD_1.jpg',
      productName: 'wooden cabinet',
      productSpecies: 'cabinet',
      price: '680',
      salesPrice: undefined,
    },
    {
      id: 54,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092-600-BLACK_1.jpg',
      productName: 'modern desk',
      productSpecies: 'desk',
      price: '520',
      salesPrice: undefined,
    },
    {
      id: 55,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T117-BROWN_1.jpg',
      productName: 'outdoor table',
      productSpecies: 'table',
      price: '400',
      salesPrice: undefined,
    },
    {
      id: 56,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093S-BLACK_1.jpg',
      productName: 'modern chair',
      productSpecies: 'chair',
      price: '290',
      salesPrice: undefined,
    },
    {
      id: 57,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093-BLACK_1.jpg',
      productName: 'lounge sofa',
      productSpecies: 'sofa',
      price: '1250',
      salesPrice: undefined,
    },
    {
      id: 58,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092PRO-GOLD_1.jpg',
      productName: 'garden bench',
      productSpecies: 'bench',
      price: '370',
      salesPrice: undefined,
    },
    {
      id: 59,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092-600-BLACK_1.jpg',
      productName: 'hallway mirror',
      productSpecies: 'mirror',
      price: '260',
      salesPrice: undefined,
    },
    {
      id: 60,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T117-BROWN_1.jpg',
      productName: 'classic sofa',
      productSpecies: 'sofa',
      price: '1450',
      salesPrice: undefined,
    },
    {
      id: 61,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093S-BLACK_1.jpg',
      productName: 'stylish chair',
      productSpecies: 'chair',
      price: '380',
      salesPrice: undefined,
    },
    {
      id: 62,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T093-BLACK_1.jpg',
      productName: 'bar stool',
      productSpecies: 'stool',
      price: '150',
      salesPrice: undefined,
    },
    {
      id: 63,
      path: 'https://icrhome.ge/dist/assets/images/catalog/250/T092PRO-GOLD_1.jpg',
      productName: 'side table',
      productSpecies: 'table',
      price: '200',
      salesPrice: undefined,
    },
  ];
  blogData: IBlog[] = [
    {
      id: 1,
      imgPath:
        'https://icrhome.ge/assets/images/blog/9a10d436963311ed9d649600004af6a4.jpg',
      title: 'ნატერიალი',
      text: 'მოაწყვეთ თქვენი ეზო, ბაღი ან ტერასა ფრანგული ბრენდის ტრენდული გარე ავეჯით !',
    },
    {
      id: 2,
      imgPath:
        'https://icrhome.ge/assets/images/blog/964cdcc4a4aa11eebc179600004af6a4.jpg',
      title: 'B2B',
      text: 'ავეჯის, დეკორისა და განათების მულტიბრენდული ჰაბი ICR HOME კორპორატიულ კლიენტებს პერსონალური ასისტენტის სერვისს სთავაზობს.',
    },
    {
      id: 3,
      imgPath:
        'https://icrhome.ge/assets/images/blog/8a8ce35a422011ec9d649600004af6a4.jpg',
      title: 'ინტერიერის აქსესუარები, რომლებიც ქმნიან განწყობას',
      text: 'მიუხედავად იმისა, რომ ავეჯი ბინაში ყველაზე მეტ სივრცეს იკავებს, აქსესუარები ის ნაწილია, რომელიც სახლს კონკრეტულ სტილს და ხასიათს ანიჭებს. თითოეული დეკორატიული ნივთი და აქსესუარი, რომელიც....',
    },
  ];
  footerData: any[] = [
    {
      title: 'ICR HOME',
      data: [
        { id: 1, text: 'ჩვენს შესახებ' },
        { id: 2, text: 'ხშირად დასმული კითხვები' },
        { id: 3, text: 'კონტაქტი' },
        { id: 4, text: 'B2B' },
      ],
    },
    {
      title: 'ბრენდები',
      data: [
        { id: 1, text: 'ლაბორატორია ჩემი სახლი' },
        { id: 2, text: 'მობლერი' },
        { id: 3, text: 'კარე' },
      ],
    },
    {
      title: 'შემოგვიერთდი',
      data: [
        { id: 1, text: 'Laboratory My Home' },
        { id: 2, text: 'Mobler Home' },
        { id: 3, text: 'KARE' },
      ],
    },
  ];
}
